---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elk
spec:
  version: 8.8.1
  nodeSets:
  - name: master
    config:
      node.roles: ["master", "remote_cluster_client"]
      xpack.ml.enabled: true
      xpack.license.self_generated.type: basic
      xpack.security.enabled: true
      xpack.monitoring.collection.enabled: true
    podTemplate:
      metadata:
        labels:
          app.kubernetes.io/name: master
          app.kubernetes.io/part-of: elk
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
    count: 2
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: rook-ceph-block
  - name: ingest
    config:
      node.roles: ["ingest", "remote_cluster_client"]
    podTemplate:
      metadata:
        labels:
          app.kubernetes.io/name: ingest
          app.kubernetes.io/part-of: elk
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 2
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
    count: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: rook-ceph-block
  - name: data
    config:
      node.roles: ["data", "remote_cluster_client"]
    podTemplate:
      metadata:
        labels:
          app.kubernetes.io/name: data
          app.kubernetes.io/part-of: elk
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
    count: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: rook-ceph-block
