---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: logstash
  namespace: elk
spec:
  scaleTargetRef:
    apiVersion: logstash.k8s.elastic.co/v1alpha1
    kind: Logstash
    name: logstash
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
  namespace: elk
spec:
  version: 8.8.1
  count: 1
  elasticsearchRefs:
  - name: "elasticsearch"
    clusterName: "elasticsearch"
  pipelines:
  - pipeline.id: main
    config.string: |
      input {
        beats {
          port => 5044
        }
      }
      output {
        elasticsearch {
          hosts => [ "https://${ELASTICSEARCH_HOST}:9200" ]
          user => "${ELASTICSEARCH_USERNAME}"
          password => "${ELASTICSEARCH_PASSWORD}"
          ssl_certificate_authorities => ["/usr/share/logstash/config/elasticsearch-certs/ca.crt"]
        }
      }
  podTemplate:
    metadata:
      labels:
        app.kubernetes.io/name:  logstash
        app.kubernetes.io/part-of: elk
    spec:
      containers:
      - name: logstash
        env:
        - name: LS_JAVA_OPTS   
          value: "-Xmx1g -Xms1g"
        - name: ELASTICSEARCH_HOST
          value: elasticsearch-es-http.elk.svc
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-es-elastic-user
              key: elastic
        volumeMounts:
        - mountPath: /usr/share/logstash/config/elasticsearch-certs
          name: elasticsearch-certs
          readOnly: true
      volumes:
      - name: elasticsearch-certs
        secret:
          defaultMode: 420
          optional: false
          secretName: kibana-kb-es-ca
  services:
  - name: beats
    service:
      spec:
        type: NodePort
        ports:
        - port: 5044
          name: "filebeat"
          protocol: TCP
          targetPort: 5044
